# The name of this site
# This text displays in the back-office and
# can be used in templates through the site.name global variable
name: "Joh. C. Henschen"

# The site's subdomain
# This option is for sites on multi-site engines
# The value determines where the site can be accessed under the engine's primary domain
subdomain: Henschen

# An array of domain aliases for the site
# This option is for sites on multi-site engines
# domains: [www.example.com, example.com]

# An array of locales (languages) the site is available in
# The locale listed first is the site's default locale
# Locales are specified using ISO language codes
# Possible locales include: en, de, fr, pl, pt-BR, it, nl, nb, es, ru, et, ja, zh-CN
locales: [de, en, ja]

# The site's timezone
# This converts the server's time to the site's time zone in templates
# The TimeZone class from Rail's ActiveSupport is used to interpret the string
# Sample timezone strings: Tokyo, Beijing, Moscow, Cairo, Paris, Pacific Time (US & Canada)
# timezone: Paris

# For SEO purposes, sites may wish to add a relevant string to the <title> tag
# And include <meta type="keywords"> and <meta type="description">
# For this purpose you can set values for these variables here
# They can be accessed in templates through the site.seo_title, site.meta_keywords, and site.meta_description variables
seo_title: 
  de: Überseespedition
  en: Oversees shipping
  ja: 海外発送

meta_keywords: 
  de: "spedition lager Lagerhaus Bremen Henschen"
  en: "forwarding warehouse warehouse Bremen Henschen"
  ja: "フォワーディング、倉庫倉庫ブレーメンヘンシェン"
meta_description: 
  de: "Überseespedition und Lagerhaus, Bremen seit 1849"
  en: "Overseas Forwarding and Warehouse, Bremen since 1849"
  ja: "海外転送と倉庫、ブレーメン1849年"

