# Your translations go here. To be used with the 'translate' liquid filter
# Example:
#   {{ 'hello_world' | translate }}
#

# hello_world:
#   en: Hello world !
#   fr: Bonjour le monde !
en:
  ja: Japanese
  de: German

ja:
  en: 日本語
  de: ドイツ語

de:
  en: Englisch
  ja: Japanisch
  
home_page:
  en: Home
  ja: ホーム
  de: Zuhause ;)

read_more:
  en: Read More
  ja: もっと見る
  de: Mehr Lesen

posted_at_format:
  en: 'Posted at %-I:%M %p on %B, %-d %Y'
  de: 'Gepostet am  %-I:%M %p on %B, %-d %Y'
  ja: '%Y年%-m月%-d日 %H:%M'
